# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deep_thought.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2
import nes_pb2 as nes__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='deep_thought.proto',
  package='org.beachc.deep_thought',
  syntax='proto3',
  serialized_pb=_b('\n\x12\x64\x65\x65p_thought.proto\x12\x17org.beachc.deep_thought\x1a\x0c\x63ommon.proto\x1a\tnes.proto\"\x84\x02\n\nVideoFrame\x12\x36\n\traw_frame\x18\x01 \x01(\x0b\x32!.org.beachc.deep_thought.RawRGB32H\x00\x12:\n\x0bsprite_list\x18\x02 \x01(\x0b\x32#.org.beachc.deep_thought.SpriteListH\x00\x12<\n\x0cregion_graph\x18\x03 \x01(\x0b\x32$.org.beachc.deep_thought.RegionGraphH\x00\x12<\n\rmachine_state\x18\x04 \x01(\x0b\x32%.org.beachc.deep_thought.MachineStateB\x06\n\x04\x64\x61ta\"b\n\x0cMachineState\x12I\n\x11nes_console_state\x18\x01 \x01(\x0b\x32,.org.beachc.deep_thought.nes.NESConsoleStateH\x00\x42\x07\n\x05state\"N\n\x08RawRGB32\x12\x34\n\x05shape\x18\x01 \x01(\x0b\x32%.org.beachc.deep_thought.common.Shape\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\">\n\nSpriteList\x12\x30\n\x07sprites\x18\x01 \x03(\x0b\x32\x1f.org.beachc.deep_thought.Sprite\">\n\x06Sprite\x12\x34\n\x05shape\x18\x01 \x01(\x0b\x32%.org.beachc.deep_thought.common.Shape\"\r\n\x0bRegionGraph2g\n\x08\x45mulator\x12[\n\tplay_game\x12%.org.beachc.deep_thought.MachineState\x1a#.org.beachc.deep_thought.VideoFrame(\x01\x30\x01\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,nes__pb2.DESCRIPTOR,])




_VIDEOFRAME = _descriptor.Descriptor(
  name='VideoFrame',
  full_name='org.beachc.deep_thought.VideoFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_frame', full_name='org.beachc.deep_thought.VideoFrame.raw_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sprite_list', full_name='org.beachc.deep_thought.VideoFrame.sprite_list', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='region_graph', full_name='org.beachc.deep_thought.VideoFrame.region_graph', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='machine_state', full_name='org.beachc.deep_thought.VideoFrame.machine_state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='org.beachc.deep_thought.VideoFrame.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=73,
  serialized_end=333,
)


_MACHINESTATE = _descriptor.Descriptor(
  name='MachineState',
  full_name='org.beachc.deep_thought.MachineState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nes_console_state', full_name='org.beachc.deep_thought.MachineState.nes_console_state', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='state', full_name='org.beachc.deep_thought.MachineState.state',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=335,
  serialized_end=433,
)


_RAWRGB32 = _descriptor.Descriptor(
  name='RawRGB32',
  full_name='org.beachc.deep_thought.RawRGB32',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='org.beachc.deep_thought.RawRGB32.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='org.beachc.deep_thought.RawRGB32.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=435,
  serialized_end=513,
)


_SPRITELIST = _descriptor.Descriptor(
  name='SpriteList',
  full_name='org.beachc.deep_thought.SpriteList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sprites', full_name='org.beachc.deep_thought.SpriteList.sprites', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=577,
)


_SPRITE = _descriptor.Descriptor(
  name='Sprite',
  full_name='org.beachc.deep_thought.Sprite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='shape', full_name='org.beachc.deep_thought.Sprite.shape', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=579,
  serialized_end=641,
)


_REGIONGRAPH = _descriptor.Descriptor(
  name='RegionGraph',
  full_name='org.beachc.deep_thought.RegionGraph',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=643,
  serialized_end=656,
)

_VIDEOFRAME.fields_by_name['raw_frame'].message_type = _RAWRGB32
_VIDEOFRAME.fields_by_name['sprite_list'].message_type = _SPRITELIST
_VIDEOFRAME.fields_by_name['region_graph'].message_type = _REGIONGRAPH
_VIDEOFRAME.fields_by_name['machine_state'].message_type = _MACHINESTATE
_VIDEOFRAME.oneofs_by_name['data'].fields.append(
  _VIDEOFRAME.fields_by_name['raw_frame'])
_VIDEOFRAME.fields_by_name['raw_frame'].containing_oneof = _VIDEOFRAME.oneofs_by_name['data']
_VIDEOFRAME.oneofs_by_name['data'].fields.append(
  _VIDEOFRAME.fields_by_name['sprite_list'])
_VIDEOFRAME.fields_by_name['sprite_list'].containing_oneof = _VIDEOFRAME.oneofs_by_name['data']
_VIDEOFRAME.oneofs_by_name['data'].fields.append(
  _VIDEOFRAME.fields_by_name['region_graph'])
_VIDEOFRAME.fields_by_name['region_graph'].containing_oneof = _VIDEOFRAME.oneofs_by_name['data']
_MACHINESTATE.fields_by_name['nes_console_state'].message_type = nes__pb2._NESCONSOLESTATE
_MACHINESTATE.oneofs_by_name['state'].fields.append(
  _MACHINESTATE.fields_by_name['nes_console_state'])
_MACHINESTATE.fields_by_name['nes_console_state'].containing_oneof = _MACHINESTATE.oneofs_by_name['state']
_RAWRGB32.fields_by_name['shape'].message_type = common__pb2._SHAPE
_SPRITELIST.fields_by_name['sprites'].message_type = _SPRITE
_SPRITE.fields_by_name['shape'].message_type = common__pb2._SHAPE
DESCRIPTOR.message_types_by_name['VideoFrame'] = _VIDEOFRAME
DESCRIPTOR.message_types_by_name['MachineState'] = _MACHINESTATE
DESCRIPTOR.message_types_by_name['RawRGB32'] = _RAWRGB32
DESCRIPTOR.message_types_by_name['SpriteList'] = _SPRITELIST
DESCRIPTOR.message_types_by_name['Sprite'] = _SPRITE
DESCRIPTOR.message_types_by_name['RegionGraph'] = _REGIONGRAPH
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoFrame = _reflection.GeneratedProtocolMessageType('VideoFrame', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOFRAME,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.VideoFrame)
  ))
_sym_db.RegisterMessage(VideoFrame)

MachineState = _reflection.GeneratedProtocolMessageType('MachineState', (_message.Message,), dict(
  DESCRIPTOR = _MACHINESTATE,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.MachineState)
  ))
_sym_db.RegisterMessage(MachineState)

RawRGB32 = _reflection.GeneratedProtocolMessageType('RawRGB32', (_message.Message,), dict(
  DESCRIPTOR = _RAWRGB32,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.RawRGB32)
  ))
_sym_db.RegisterMessage(RawRGB32)

SpriteList = _reflection.GeneratedProtocolMessageType('SpriteList', (_message.Message,), dict(
  DESCRIPTOR = _SPRITELIST,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.SpriteList)
  ))
_sym_db.RegisterMessage(SpriteList)

Sprite = _reflection.GeneratedProtocolMessageType('Sprite', (_message.Message,), dict(
  DESCRIPTOR = _SPRITE,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.Sprite)
  ))
_sym_db.RegisterMessage(Sprite)

RegionGraph = _reflection.GeneratedProtocolMessageType('RegionGraph', (_message.Message,), dict(
  DESCRIPTOR = _REGIONGRAPH,
  __module__ = 'deep_thought_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.RegionGraph)
  ))
_sym_db.RegisterMessage(RegionGraph)



_EMULATOR = _descriptor.ServiceDescriptor(
  name='Emulator',
  full_name='org.beachc.deep_thought.Emulator',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=658,
  serialized_end=761,
  methods=[
  _descriptor.MethodDescriptor(
    name='play_game',
    full_name='org.beachc.deep_thought.Emulator.play_game',
    index=0,
    containing_service=None,
    input_type=_MACHINESTATE,
    output_type=_VIDEOFRAME,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EMULATOR)

DESCRIPTOR.services_by_name['Emulator'] = _EMULATOR

# @@protoc_insertion_point(module_scope)
