# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='nes.proto',
  package='org.beachc.deep_thought.nes',
  syntax='proto3',
  serialized_pb=_b('\n\tnes.proto\x12\x1borg.beachc.deep_thought.nes\x1a\x0c\x63ommon.proto\"\x87\x02\n\x0fNESConsoleState\x12\x46\n\rplayer1_input\x18\x01 \x01(\x0b\x32/.org.beachc.deep_thought.nes.NESControllerState\x12\x46\n\rplayer2_input\x18\x02 \x01(\x0b\x32/.org.beachc.deep_thought.nes.NESControllerState\x12\r\n\x05power\x18\x03 \x01(\x08\x12\r\n\x05reset\x18\x04 \x01(\x08\x12\x12\n\ninsertGame\x18\x05 \x01(\x08\x12\x32\n\x04game\x18\x06 \x01(\x0b\x32$.org.beachc.deep_thought.common.Game\"\xd7\x01\n\x12NESControllerState\x12\x32\n\x04\x64pad\x18\x01 \x01(\x0b\x32$.org.beachc.deep_thought.common.DPad\x12\x0e\n\x06select\x18\x02 \x01(\x08\x12\r\n\x05start\x18\x03 \x01(\x08\x12\t\n\x01\x61\x18\x04 \x01(\x08\x12\t\n\x01\x62\x18\x05 \x01(\x08\x12\x0f\n\x07trurboA\x18\x06 \x01(\x08\x12\x0f\n\x07trurboB\x18\x07 \x01(\x08\x12\x36\n\x06player\x18\x08 \x01(\x0b\x32&.org.beachc.deep_thought.common.Player\"\xbc\x02\n\x0fNestopiaControl\x12\x10\n\x08\x61ltspeed\x18\x01 \x01(\x08\x12\x13\n\x0binsertcoin1\x18\x02 \x01(\x08\x12\x13\n\x0binsertcoin2\x18\x03 \x01(\x08\x12\x0f\n\x07\x66\x64sflip\x18\x04 \x01(\x08\x12\x11\n\tfdsswitch\x18\x05 \x01(\x08\x12\x0e\n\x06qsave1\x18\x06 \x01(\x08\x12\x0e\n\x06qsave2\x18\x07 \x01(\x08\x12\x0e\n\x06qload1\x18\x08 \x01(\x08\x12\x0e\n\x06qload2\x18\t \x01(\x08\x12\x12\n\nscreenshot\x18\n \x01(\x08\x12\r\n\x05reset\x18\x0b \x01(\x08\x12\x0f\n\x07rwstart\x18\x0c \x01(\x08\x12\x0e\n\x06rwstop\x18\r \x01(\x08\x12\x12\n\nfullscreen\x18\x0e \x01(\x08\x12\x0e\n\x06\x66ilter\x18\x0f \x01(\x08\x12\x13\n\x0bscalefactor\x18\x10 \x01(\x08\x12\x0c\n\x04quit\x18\x11 \x01(\x08\x62\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])




_NESCONSOLESTATE = _descriptor.Descriptor(
  name='NESConsoleState',
  full_name='org.beachc.deep_thought.nes.NESConsoleState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player1_input', full_name='org.beachc.deep_thought.nes.NESConsoleState.player1_input', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player2_input', full_name='org.beachc.deep_thought.nes.NESConsoleState.player2_input', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='power', full_name='org.beachc.deep_thought.nes.NESConsoleState.power', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset', full_name='org.beachc.deep_thought.nes.NESConsoleState.reset', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertGame', full_name='org.beachc.deep_thought.nes.NESConsoleState.insertGame', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='game', full_name='org.beachc.deep_thought.nes.NESConsoleState.game', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=320,
)


_NESCONTROLLERSTATE = _descriptor.Descriptor(
  name='NESControllerState',
  full_name='org.beachc.deep_thought.nes.NESControllerState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dpad', full_name='org.beachc.deep_thought.nes.NESControllerState.dpad', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='select', full_name='org.beachc.deep_thought.nes.NESControllerState.select', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='start', full_name='org.beachc.deep_thought.nes.NESControllerState.start', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a', full_name='org.beachc.deep_thought.nes.NESControllerState.a', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b', full_name='org.beachc.deep_thought.nes.NESControllerState.b', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trurboA', full_name='org.beachc.deep_thought.nes.NESControllerState.trurboA', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='trurboB', full_name='org.beachc.deep_thought.nes.NESControllerState.trurboB', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='player', full_name='org.beachc.deep_thought.nes.NESControllerState.player', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=538,
)


_NESTOPIACONTROL = _descriptor.Descriptor(
  name='NestopiaControl',
  full_name='org.beachc.deep_thought.nes.NestopiaControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='altspeed', full_name='org.beachc.deep_thought.nes.NestopiaControl.altspeed', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertcoin1', full_name='org.beachc.deep_thought.nes.NestopiaControl.insertcoin1', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='insertcoin2', full_name='org.beachc.deep_thought.nes.NestopiaControl.insertcoin2', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fdsflip', full_name='org.beachc.deep_thought.nes.NestopiaControl.fdsflip', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fdsswitch', full_name='org.beachc.deep_thought.nes.NestopiaControl.fdsswitch', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qsave1', full_name='org.beachc.deep_thought.nes.NestopiaControl.qsave1', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qsave2', full_name='org.beachc.deep_thought.nes.NestopiaControl.qsave2', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qload1', full_name='org.beachc.deep_thought.nes.NestopiaControl.qload1', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='qload2', full_name='org.beachc.deep_thought.nes.NestopiaControl.qload2', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='screenshot', full_name='org.beachc.deep_thought.nes.NestopiaControl.screenshot', index=9,
      number=10, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reset', full_name='org.beachc.deep_thought.nes.NestopiaControl.reset', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rwstart', full_name='org.beachc.deep_thought.nes.NestopiaControl.rwstart', index=11,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rwstop', full_name='org.beachc.deep_thought.nes.NestopiaControl.rwstop', index=12,
      number=13, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='fullscreen', full_name='org.beachc.deep_thought.nes.NestopiaControl.fullscreen', index=13,
      number=14, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filter', full_name='org.beachc.deep_thought.nes.NestopiaControl.filter', index=14,
      number=15, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='scalefactor', full_name='org.beachc.deep_thought.nes.NestopiaControl.scalefactor', index=15,
      number=16, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='quit', full_name='org.beachc.deep_thought.nes.NestopiaControl.quit', index=16,
      number=17, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=541,
  serialized_end=857,
)

_NESCONSOLESTATE.fields_by_name['player1_input'].message_type = _NESCONTROLLERSTATE
_NESCONSOLESTATE.fields_by_name['player2_input'].message_type = _NESCONTROLLERSTATE
_NESCONSOLESTATE.fields_by_name['game'].message_type = common__pb2._GAME
_NESCONTROLLERSTATE.fields_by_name['dpad'].message_type = common__pb2._DPAD
_NESCONTROLLERSTATE.fields_by_name['player'].message_type = common__pb2._PLAYER
DESCRIPTOR.message_types_by_name['NESConsoleState'] = _NESCONSOLESTATE
DESCRIPTOR.message_types_by_name['NESControllerState'] = _NESCONTROLLERSTATE
DESCRIPTOR.message_types_by_name['NestopiaControl'] = _NESTOPIACONTROL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NESConsoleState = _reflection.GeneratedProtocolMessageType('NESConsoleState', (_message.Message,), dict(
  DESCRIPTOR = _NESCONSOLESTATE,
  __module__ = 'nes_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.nes.NESConsoleState)
  ))
_sym_db.RegisterMessage(NESConsoleState)

NESControllerState = _reflection.GeneratedProtocolMessageType('NESControllerState', (_message.Message,), dict(
  DESCRIPTOR = _NESCONTROLLERSTATE,
  __module__ = 'nes_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.nes.NESControllerState)
  ))
_sym_db.RegisterMessage(NESControllerState)

NestopiaControl = _reflection.GeneratedProtocolMessageType('NestopiaControl', (_message.Message,), dict(
  DESCRIPTOR = _NESTOPIACONTROL,
  __module__ = 'nes_pb2'
  # @@protoc_insertion_point(class_scope:org.beachc.deep_thought.nes.NestopiaControl)
  ))
_sym_db.RegisterMessage(NestopiaControl)


# @@protoc_insertion_point(module_scope)
